### ISSUE TITLE
Add Flow / TypeScript?

### ISSUE THREAD

**Issue by iRoachie** [cooperka/react-native-snackbar#21]
Are you interested in having typings, for those using react native with typescript? I've already started on it.

**Comment by cooperka** [comment]
I've been wanting to add some sort of typings for a while now -- if you're up to the task, that would be great! The only caveat is that I would prefer to use Flow instead of TypeScript, partly because it's more popular in the React community, and also because of its type soundness.

Here's an explanation I really like that discusses some of the differences: https://discuss.reactjs.org/t/if-typescript-is-so-great-how-come-all-notable-reactjs-projects-use-babel/4887/2

Would you be willing to implement typings using Flow?

**Comment by iRoachie** [comment]
Well sure, I actually have two projects using your library, one with flow and other typescript. Having both works for me :D

**Comment by cooperka** [comment]
Typescript has been merged; I'll keep this issue open for now until I get a chance to add Flow.

**Comment by iRoachie** [comment]
I found the documentation around it kinda sketchy. If you have any useful links i'll be glad to do. Would we be submitting to the flow-typed [repo](https://github.com/flowtype/flow-typed) ? Is there a way to bundle it with the library?

**Comment by cooperka** [comment]
It sounds like the library definitions you linked to are for libraries that don't already use flow; sort of like a way to add remote typedefs without forking the library. Seems weird to me, I don't want to do that haha.

I was thinking of just using basic syntax in the code: https://flow.org/en/docs/getting-started/

It also sounds like there's a command `flow gen-flow-files` that will auto-generate `*.js.flow` files for all of your sources and output to `lib` so they're available for consumers of the module.

**Comment by iRoachie** [comment]
@cooperka Ooo alright then, that's simpler :D I'll take a knock at it after work
