### ISSUE TITLE
Compilation failed on iOS?

### ISSUE THREAD

**Issue by eddnav** [cooperka/react-native-snackbar#22]
I just followed the instructions, any idea why this could be happening? I fear maybe my `react-native` version may be too low (react `15.3.2`, react-native `0.35.0`.

```
The following build commands failed:
	CompileC .../ios/build/Build/Intermediates/RNSnackbar.build/Debug-iphonesimulator/RNSnackbar.build/Objects-normal/x86_64/RNSnackbar.o RNSnackbar.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by cooperka** [comment]
Hmm, I've never seen this error before. Could you try cleaning your Xcode project and building again? You can also try using the [official example app](https://github.com/cooperka/react-native-snackbar/tree/master/example) with different settings to try to narrow down what the problem is, such as RN version. Let me know either way if you find a solution or if you run into more issues!

**Comment by eddnav** [comment]
I think the problems I'm having are related to my react native version, I tried upgrading but I'm now running into more issues with the actual upgrade process, I'll close this issue for now, and let you know if I run into anything else related to this package.
