### ISSUE TITLE
Snackbar accessibility label.

### ISSUE THREAD

**Issue by SitCode1993** [cooperka/react-native-snackbar#44]
Hi,

I just realized that the snacker does not accept that accessibilityLabel option, I think it would be nice to have them accepting this

**Comment by cooperka** [comment]
Hi @SitCode1993, thanks for bringing this up. It's a bit messy to pass accessibility labels through to native code, but if you send a PR I will gladly accept it!

I would hope Android has good support for this since it's a native Android snackbar, and it should be fairly straightforward to add on the iOS view as well.

**Comment by cooperka** [comment]
By the way @SitCode1993, have you seen this PR? https://github.com/cooperka/react-native-snackbar/pull/45

It hard-coded the `accessibilityIdentifier` to `"snackbar"`; this may be enough for most people. Let me know if there's a particular use-case you still want to be supported. Thanks!

**Comment by dantman** [comment]
@cooperka `accessibilityIdentifier` and `accessibilityLabel` are two different things. The former is an id that doesn't actually have much to do with accessibility. The later is text that gets read to the user.

**Comment by cooperka** [comment]
Thanks @dantman. I tested the Snackbar using the iOS Accessibility Inspector and it seems to read the text displayed on the Snackbar as expected (and also correctly treats the action button as a button).

I'd certainly accept a PR allowing customization of the accessibility label, but I'll leave this issue closed as it's unlikely to be done.
