### ISSUE TITLE
npm install not working 

### ISSUE THREAD

**Issue by chetankotkar** [cooperka/react-native-snackbar#53]
installation stuck at 
[          ........] | extract:fsevents: sill extract react-native-snackbar@0.4.4

**Comment by cooperka** [comment]
That's very strange, could you clean and try again? At least `rm -rf node_modules`. You could also try [Yarn](https://yarnpkg.com/en/docs/getting-started) instead of npm.

**Comment by pavanmehta91** [comment]
same issue. Tried removing the node_modules too.

**Comment by cooperka** [comment]
@pavanmehta91 have you tried using Yarn, and also cleaning other things e.g. `yarn cache clean`?

**Comment by cooperka** [comment]
@chetankotkar were you ever able to resolve this issue?

**Comment by pavanmehta91** [comment]
I could install it with npm only. :)

**Comment by chetankotkar** [comment]
@cooperka  npm with **--no-optional** helped me. perhaps I dont know what are optional dependencies.

**Comment by cooperka** [comment]
Thanks for the tip, @chetankotkar! Glad you both got it working.

Some libraries include [optional dependencies](https://docs.npmjs.com/files/package.json#optionaldependencies), of which `fsevents` is often one. It isn't supported by many Linux OSes so it's simply ignored. I'm not sure if that's part of the reason here.

Note: I can install `react-native-snackbar` just fine on Ubuntu.
