### ISSUE TITLE
Support for right-to-left (RTL) layout

### ISSUE THREAD

**Issue by karimkhamwani** [cooperka/react-native-snackbar#62]

**Comment by cooperka** [comment]
I haven't tested it but I imagine it's not yet supported. The code is quite simple, please feel free to submit a PR!

**Comment by karimkhamwani** [comment]
not supported. please release asap

**Comment by cooperka** [comment]
Hi @karimkhamwani, I'm an independent developer who created this library in my own spare time and released it to you for free. Your request comes off as insistent rather than constructive, which doesn't exactly inspire me to work for you.

If you'd like to help contribute this feature, I'd be happy to merge a pull request and release it. That's what the open-source community is all about! Let me know if you'd like any resources on getting started contributing to open-source and I can provide you with some links.

**Comment by mehranabi** [comment]
Hello @cooperka , Thanks for this work!
It's totally working on RTL layouts, and everything's good in RTL Farsi (Persian) layout which i tested.

**Comment by cooperka** [comment]
Thanks for confirming @mehranabi! I'll close this.
